### ISSUE TITLE
Signup Bugs

### ISSUE THREAD

**Issue by CaptainFreak** [NITG-Aficionados/Leaderboard#5]
There are many bugs in signup currently, like:
1. Username with duplicate names is allowed.
2. Leaderboard ranking is not correct after new User signup.
3. Duplicate email check.

**Comment by mgautam98** [comment]
For Duplicate username and Email I am changing schema of user and profile. Also I will handle the error that database gives when someone tries registering with duplicate email or username.

**Comment by CaptainFreak** [comment]
Go ahead @mgautam98

**Comment by CaptainFreak** [comment]
Also look into the weird issues with leader-board ranking, checkout the live hosted version.

**Comment by mgautam98** [comment]
PR #20 closes this issue.
Leaderboard ranking issuse is handled by issue #3
